# 开发环境配置

# 数据源配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: opm
    password: System11
    type: com.alibaba.druid.pool.DruidDataSource