# 端口
server:
  port: 8081

# 多环境配置
spring:
  profiles:
    active: dev

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/xzsoft/**/*Mapper.xml
  typeAliasesPackage: com.xzsoft.**.entity
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
